name: Lint ROS2 Foxy reachy_kinematics package
on: [push]

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, mypy, pep257, pep8, xmllint]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        linter: ${{ matrix.linter }}
        package-name: reachy_kinematics