name: Lint ROS2 Foxy reachy_kinematics package
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
          linter: [flake8]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-python@v2
      with:
        python-versions: '3.8'

    - name: Lint with flake8
      run: |
        pip install -e flake8 flake8-docstrings
        flake8 . --count --show-source --statistics