name: Lint ROS2 Foxy reachy_kinematics package
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Lint with flake8
      run: |
        pip install flake8 flake8-docstrings
        python -m flake8 . --count --show-source --statistics